name: Daily Crawler

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Chrome & ChromeDriver 114
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl

        # Install Chrome 114
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.133-1_amd64.deb
        sudo dpkg -i google-chrome*.deb || sudo apt-get -f install -y

        # Install ChromeDriver 114
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

        # Debug print
        google-chrome --version
        chromedriver --version

    - name: Run crawler
      run: python aitimes_crawler.py
